version: '3'

services:
  app:
    build: .
    entrypoint: ./.docker/entrypoint.sh
    container_name: api-nest-venda
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app

  db:
    build: ./.docker/mysql
    container_name: nest-db-venda
    restart: always
    tty: true
    ports:
      - "33006:3306"
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nest-venda
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root